resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: github_xin
      path: xingao0803/Pipeline-examples
      branches:
        include: master
  - name: DockerAppImage
    type: Image
    configuration:
      registry: artidocker
      sourceRepository: docker-local
      imageName: docker.artifactory/swampup_docker_app_demo
      imageTag: '${run_number}'
      autoPull: true
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
      buildName: SampleApp
      buildNumber: 1


pipelines:
  - name: swampup_docker_app_pipeline
    configuration:
      environmentVariables:
        readOnly:
           my_env_var: '1.0.$run_number'
           ArtIP: $(echo ${int_ArtifactoryUnified_url}|awk -F '/' '{print $3}'|awk -F ':' '{print $1}')
    steps:
